### ISSUE TITLE
Add touch events for iOS

### ISSUE THREAD

**Issue by Haargeeel** [cedricdelpoux/react-svg-piechart#10]
Hi,
I realised that the `onSectorHover` doesn't work for iOS touch gestures. But there is more than one way to implement it and I'm not sure how optional you would want to add this feature.

1. Just adding `onTouchStart`

```
        return (
          <path
            key={'sector' + i}
            d={dPath}
            fill={d.color || palette[i % palette.length]}
            stroke='#fff'
            strokeWidth={sectorStrokeWidth}
            onTouchStart={() => this.handleSectorHover(i)}
            // onTouchEnd for only expanding while touching?
            onMouseEnter={() => this.handleSectorHover(i)}
            onMouseLeave={() => this.handleSectorHover(null)}
          />
        )
```

2. Make it optional:

```
<PieChart
  data={ data }
  expandedSector={expandedSector}
  onSectorHover={this.handleMouseEnterOnSector}
  sectorStrokeWidth={2}
  expandOnHover
  expandOnTouch // optional
/>
```

You library is cool because it's very lightweight so I did not want to add big conditions (2. solution) in the code if you like the first approach more.

Cheers

**Comment by cedricdelpoux** [comment]
Hi, Thank you for reporting this bug. 

I agree to add the `onTouchStart` and `onTouchEnd` events and make this optional.
Could you open a PR with this?

Thank you very much

**Comment by Haargeeel** [comment]
#11

**Comment by Haargeeel** [comment]
Here you go: #11
