### ISSUE TITLE
Error in path attribute

### ISSUE THREAD

**Issue by Jothipriyashekhar** [cedricdelpoux/react-svg-piechart#12]
Iam getting this error ..

Error: <path> attribute d: Expected number, "… A150,150 0 1,1 NaN,NaN z".

**Comment by cedricdelpoux** [comment]
Can you give me your data?

**Comment by Jothipriyashekhar** [comment]
Hi
     Find my data below


const data = [
{
label: "Billable",
value: this.state.billableCount,
color: "#F9CB40"
}, {
label: "Non-billable",
value: this.state.nonbillableCount,
color: "#FF715B"
}, {
label: "Free",
value: this.state.FreeCount,
color: "#BCED09"
}, {
label: "Support",
value: this.state.supportCount,
color: "#2F52E0"
}
]

**Comment by xuopled** [comment]
Thank you. I will take a look asap.

**Comment by cedricdelpoux** [comment]
@Jothipriyashekhar I think the problem is that your values can be null because it s dependent of the state
