### ISSUE TITLE
Peer dependency with react

### ISSUE THREAD

**Issue by mengchen2** [cedricdelpoux/react-svg-piechart#13]
We got following issue when we were trying to build our app on Altus.  
npm WARN react-svg-piechart@1.3.0 requires a peer of react@~15.3.0 but none was installed.

Is it possible we make the peer dependency for this plug more flexible? like 
  "peerDependencies": {
    "react": "^15.3.0"
  },

**Comment by cedricdelpoux** [comment]
Of course, I will do it. Thank you for your feedback

**Comment by cedricdelpoux** [comment]
@mengchen2 I just release v1.4.0
