### ISSUE TITLE
The pie chart won't show 100% when only one value is 1 and rest are 0. It just disappears from view. How can this be done ?

### ISSUE THREAD

**Issue by varvarasd** [cedricdelpoux/react-svg-piechart#14]
I'm trying to use this pie chart but in my case I'm having only two objects in data, one with value 1 and one with 0, when just one value is 1 the pie chart should show 100% but it just disappears. Do you guys have a solution for this or maybe suggest other piecharts which have this option? it would be greatly appreciated.

Many thanks.

**Comment by cedricdelpoux** [comment]
It sounds like a bug. I will fix it. Thank you for your feedback

**Comment by varvarasd** [comment]
I'm also getting this error in console:
```
Error: <path> attribute d: Expected number, "… A150,150 0 1,1 NaN,NaN z".
Error: <path> attribute d: Expected number, "M150,150 LNaN,NaN A150,150…".
```

**Comment by cedricdelpoux** [comment]
Can you give me your `data` object please ?

**Comment by varvarasd** [comment]
```
var data = [{
                 label: "Active",
                 value: 0,
                 color: "#26C281",
            },{
                 label: "Inactive",
                 value: 0,
                 color: "#D91E18"
            }];
let {services} = this.props.data;
for(var i = 0; i < services.length; i++) {
                if(services[i].provisioning_state === "active") {
                    data[0].value++ ;
                } else {
                    data[1].value++ ;
                }
            }
```

**Comment by cedricdelpoux** [comment]
@varvarasd You should check version `v2.0.1`

I think the problem is gone. Thank you for reporting this
