### ISSUE TITLE
The wrong color is used when one of the values is 0  - using ver 2.0.2

### ISSUE THREAD

**Issue by fairps** [cedricdelpoux/react-svg-piechart#16]
We are passing in 2 values in data:  a 0 and a 1.  We get the full circle drawn as expected but it is drawn in the color for the 1st value which is 0 and not for the second value which is 1.  What we see and the Props from the React debug tool:

![image](https://user-images.githubusercontent.com/27831128/35071922-1e5a194a-fba8-11e7-8021-9973848f166b.png)

Props
  data: Array[2]
    0:{…}
      color: "#2ecc71"    <--- green color
      value: 0
    1:{…}
      color: "#3498db"   <--- blue color
      value: 1

  expandOnHover: false
  expandSize: 5
  onSectorHover: null
  sectorStrokeWidth: 1
  shrinkOnTouchEnd: false
  strokeColor: "#fff"
  strokeLinejoin: "round"
  strokeWidth: 1
  viewBoxSize: 100

**Comment by cedricdelpoux** [comment]
Hi @fairps, thank you for reporting this bug. I will try to reproduce

**Comment by cedricdelpoux** [comment]
Indeed ! I fixed the bug. Please checkout v2.0.3 from npm

**Comment by fairps** [comment]
Thanks so much!  Y'all have provided a really nice control!!

**Comment by cedricdelpoux** [comment]
You are welcome. Thank you for using this lib 🙂
