### ISSUE TITLE
Change the overall size in an html page

### ISSUE THREAD

**Issue by amActiveHello** [cedricdelpoux/react-svg-piechart#23]
1、my code set style height={300}, but it has no effect , how do i set to change the whole pie size , 
while viewBoxSize don't change <svg />'s height .
`<PieChart
    data={Piedata}
    // If you need expand on hover (or touch) effect
    expandOnHover
    expandSize={1}
    // If you need custom behavior when sector is hovered (or touched)
     viewBoxSize={15}
    strokeWidth={1}
    onSectorHover={(d, i, e) => {
      if (d) {
        console.log("Mouse enter - Index:", i, "Data:", d, "Event:", e)
      } else {
        console.log("Mouse leave - Index:", i, "Event:", e)
      }   
    }}  
    style={{height: 300}}

  />  
`

**Comment by cedricdelpoux** [comment]
Try to set the container height. Not the `PieChart` component itself

**Comment by amActiveHello** [comment]
thanks ,now it's ok.

**Comment by cedricdelpoux** [comment]
Perfect ! I close the issue. Thank you
