### ISSUE TITLE
Chart isn't responsive

### ISSUE THREAD

**Issue by nkovalenko93** [cedricdelpoux/react-svg-piechart#3]
•Facebook : 100
•Twitter : 60
•Google Plus : 1
•Pinterest : 2
•Linked In : 1

Run chart with that parameters. You'll see chart isn't responsive... Component can't draw adequately with other parameters.
Chunk with the biggest value drown with small width.

**Comment by cedricdelpoux** [comment]
Hi @kol9n93, I just published a new version. Could you check if the problem persist ?
