### ISSUE TITLE
1.1.0 requires a peer of react@^0.14.0

### ISSUE THREAD

**Issue by sonicviz** [cedricdelpoux/react-svg-piechart#6]
Hi, 
I keep getting
npm WARN react-svg-piechart@1.1.0 requires a peer of react@^0.14.0 but none was installed.

even though the latest repo shows this updated. Triggering a new NPM install doesn't do anything

**Comment by xuopled** [comment]
Hi @sonicviz I will publish a new version this week

**Comment by cedricdelpoux** [comment]
@sonicviz I just published a new version. Could you check if your problem persist ?

**Comment by sonicviz** [comment]
I managed to get the project working again without upgrading meteor and therefore running into the issue.
But if you've published it and resolved the version dependency it _should_ work fine I think.
