### ISSUE TITLE
Wrong import instructions.

### ISSUE THREAD

**Issue by aditya2337** [cedricdelpoux/react-svg-piechart#8]
I think `import { PieChart } from 'components/piechart'` is obviously wrong.

**Comment by cedricdelpoux** [comment]
Where did you find this example? 
The example in the `README` specifies:

```
import PieChart from 'react-svg-piechart'
```

**Comment by aditya2337** [comment]
In the npm store itself: [here](https://www.npmjs.com/package/react-svg-piechart)

**Comment by cedricdelpoux** [comment]
Ok, I need to publish a new npm release. The `README` of this repo is up to date

**Comment by cedricdelpoux** [comment]
I just published the `v1.2.1` release to fix this :) Thank you very much

**Comment by aditya2337** [comment]
Sure man
